config/routes.rb
Jfeed::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  resources :users

  resources :jobs do
    collection do
      get "job_location"
      get "job_search"
      get  'post_job' => :new
    end
  end

  controller :information do
    get "contact"
    get "about"
    get "sitemap_ibo"
    get "interviewer"
    get "redundancyadvice"
  end

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  mount Ckeditor::Engine => "/ckeditor"

   root :to => 'jobs#index'

end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :ad_expires_on, :ad_posting_on, :company_name, :company_website, :contact_email, :contact_name, :contact_number, :experience, :location, :position, :qualification, :responsibility, :skill
  validates :company_name, :location, :position, :qualification, :presence => true


  def self.location_type
    [
     ['Hyderabad','hyderabad'],
     ['Bangalore','bangalore'],
     ['Chennai','chennai'],
     ['Pune','pune'],
     ['Delhi','delhi'],
     ['Mumbai','mumbai'],
     ['Haryana,Noida','haryana'],
     ['Cochin,Kerala','cochin'],
     ['Kochi,Kerala','kochi'],
     ['Gurgaon(New Delhi)','gurgaon'],
     ['Kolkatha','kolkatha'],
     ['Other City','other'],
     ['Across India','across_india']
    ]
  end

  def self.location_type_to_value
    [
      "hyderabad" => "Hyderabad",
      "bangalore" => "Bangalore",
      "chennai" => "Chennai",
      "pune" => "Pune",
      "delhi" => "Delhi",
      "mumbai" => "Mumbai",
      "haryana" => "Haryana,Noida",
      "cochin" => "Cochin,Kerala",
      "kochi" => "Kochi,Kerala",
      "gurgaon" => "Gurgaon(New Delhi)",
      "kolkatha" => "Kolkatha",
      "other" => "Other City",
      "across_india" => "Across India"
    ]
  end

  def self.category
    [
      ["Select a Category"],
      ["Accounting / Auditing / Tax"],
      ["Administration / Secretary / Front Office"],
      ["Architecture / Civil Engineering"],
      ["Art / Design / Creative / Fashion"],
      ["Banking / Financial Services"],
      ["Construction"],
      ["Consulting / Strategy / Corporate Planning"],
      ["Content / Edition / Journalism"],
      ["Customer Service / Call Centre / Operations / Data Entry"],
      ["Education / Teaching / Language"],
      ["Engineering / R&amp;D"],
      ["Executive Management"],
      ["Freshers Jobs"],
      ["Healthcare / Medical / Pharmacy"],
      ["Hotel / Restaurant / Catering"],
      ["HR / Recruitment"],
      ["Import-Export / Merchandising / Trading"],
      ["Insurance"],
      ["Internet Technologies / Web / E-Commerce"],
      ["IT - Databases / Datawarehousing"],
      ["IT - ERP / CRM"],
      ["IT - Hardware / Telecom / Support"],
      ["IT - Project Management"],
      ["IT - Software Programming / Analysis"],
      ["IT - Systems / Networking / Security"],
      ["Legal / Law"],
      ["Logistics / Purchase / Supply Chain / Procurement"],
      ["Manufacturing / Packaging / Printing / Industrial Jobs"],
      ["Marketing / Communication / Advertising / PR"],
      ["Mechanical Engineering / Mechatronics"],
      ["Media / TV / Films / Production"],
      ["Pharma, Biotech and Chemical Industry"],
      ["Project Management"],
      ["Quality / Testing / Process Control"],
      ["Real Estate / Property"],
      ["Sales / Business Development"],
      ["Security Services / Guards"],
      ["Skilled Trade / Service / Installation / Repair"],
      ["Social Services / NGOs / Nonprofit"],
      ["Travel / Reservation / Airlines"]
    ]
  end


  def self.search(search)
    if search == "Fresher"
        find(:all, :conditions => ['experience LIKE ?', "%#{search}%"])
    else
        find(:all, :conditions => ['position LIKE ?', "%#{search}%"])
    end
  end


  def to_param
    "#{id}-#{company_name.parameterize}-#{created_at.strftime('%d-%m-%Y')}"
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  skip_before_filter :authorize, :only => [:index,:show, :new, :create,:job_location,:job_search]
  before_filter :default_form_values
  # GET /jobs
  # GET /jobs.json
  def index
    #@jobs = Job.order("created_at").all
    @jobs = Job.paginate(:page => params[:page], :per_page => 50).order("created_at desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jobs }
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/new
  # GET /jobs/new.json
  def new
    @job = Job.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(params[:job])

    respond_to do |format|
      if (session[:user_id] or verify_recaptcha) and @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render json: @job, status: :created, location: @job }
      else
        format.html { render action: "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.json
  def update
    @job = Job.find(params[:id])

    respond_to do |format|
      if @job.update_attributes(params[:job])
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end

  def job_location
    #@jobs = Job.find_all_by_location(params[:location])
    @title="#{params[:location]} Jobs"
    @meta_tag_desc="Find thousands of jobs in #{params[:location]}. Search and apply online for jobs in #{params[:location]}. Begin your best job search today."
    @jobs = Job.paginate(:page => params[:page], :per_page => 50).where(:location => params[:location]).order("created_at desc")
    render :'jobs/index'
  end

  def job_search
    @title="#{params[:search]} Top 50 Best Jobs"
    @meta_tag_desc = "Search #{params[:search]} jobs in India. Search job openings on #{params[:search]}, see if they fit - company salaries, reviews, and more posted by employees"
    @jobs = Job.paginate(:page => params[:page], :per_page => 50).order("created_at desc").search(params[:search])
    render :'jobs/index'
  end

  def default_form_values
    log = CustomLogger.new("user_access")
    log.info("ip_address: #{request.remote_ip}, Url: #{request.url}")
  end


end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for @job, :html => {:class => "form-horizontal"} do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="control-group error">
    <%= f.label :company_name, :class => "control-label" %>
    <div class="controls">
    <%= f.text_field :company_name%>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :company_website , :class => "control-label" %>
    <div class="controls">
    <%= f.text_field :company_website %>
    </div>
  </div>
  <div class="control-group error">
    <%= f.label :position , :class => "control-label" %>
    <div class="controls">
    <%= f.text_field :position %>
    </div>
  </div>
  <div class="control-group error">
    <%= f.label :experience , :class => "control-label" %>
    <div class="controls">
    <%= f.text_field :experience %>
      <span class="help-inline">Example "Fresher or 1-2 Years"</span>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :location , :class => "control-label" %>
    <div class="controls">
    <%= f.select(:location, Job.location_type) %>
    </div>
  </div>
  <div class="control-group error">
    <%= f.label 'Eligibility / Qualification' , :class => "control-label" %>
    <div class="controls">
    <%= f.text_field :qualification %>
      <span class="help-inline">Example "B.E/B.Tech/MCA/ M.E /M.Tech/Ms."</span>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :ad_expires_on , :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :ad_expires_on %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :contact_name , :class => "control-label" %>
    <div class="controls">
    <%= f.text_field :contact_name %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :contact_email , :class => "control-label" %>
    <div class="controls">
    <%= f.text_field :contact_email %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :contact_number , :class => "control-label" %>
    <div class="controls">
    <%= f.text_field :contact_number %>
    <span class="help-inline">Example "9849098490"</span>
  </div>
  </div>
  <div class="control-group">
    <%= f.label 'Job Summary / Responsibility' , :class => "control-label" %>
    <div class="controls">
    <%#= f.text_area :responsibility, :rows => 3 %>
      <%= f.cktext_area :responsibility, :width => 800, :height => 200 %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label 'Skills/Experience' , :class => "control-label" %>
    <div class="controls">
    <%= f.cktext_area :skill, :width => 800, :height => 200 %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label 'Enter Text:' , :class => "control-label" %>
    <div class="controls">
    <%= recaptcha_tags %>
    </div>
  </div>
    <div class="control-group">
      <div class="controls">
             <%= f.submit 'Submit', :class => "btn" %>
      </div>
    </div>
<% end %>


<style type="text/css">


</style>

<script type='text/javascript'>
  $(function () {
    $("#job_ad_expires_on").datepicker({"format": "yyyy-mm-dd"});
  });


</script>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', root_path %>

app/views/jobs/index.html.erb
<% if @title.nil? %>
    <% @title="JobTar.com Free Job post India | Best IT/Government Jobs|Job Search" %>
<% end %>

<ul class="nav nav-pills">

  <% if false %>
  <% Job.location_type.each do |loc_name,loc_value|  %>
      <% if params[:location] == loc_value %><li class="active"><% else %><li><% end %>
        <%= link_to "#{loc_name} Jobs" , job_location_jobs_path(:location => loc_value ) %>
      </li>
  <% end %>
  <% end %>

  <% if params[:location]=="Hyderabad" %><li class="active"><% else %><li><% end %>
  <%= link_to 'Hyderabad Jobs', job_location_jobs_path(:location => "Hyderabad") %></li>

  <% if params[:location]=="Bangalore" %><li class="active"><% else %><li><% end %>
  <%= link_to 'Bangalore Jobs', job_location_jobs_path(:location => "Bangalore") %></li>

  <% if params[:location]=="Chennai" %><li class="active"><% else %><li><% end %>
  <%= link_to 'Chennai Jobs', job_location_jobs_path(:location => "Chennai") %></li>

  <% if params[:location]=="Pune" %><li class="active"><% else %><li><% end %>
  <%= link_to 'Pune Jobs', job_location_jobs_path(:location => "Pune") %></li>

  <% if params[:location]=="Mumbai" %><li class="active"><% else %><li><% end %>
  <%= link_to 'Mumbai Jobs', job_location_jobs_path(:location => "Mumbai") %></li>

  <% if params[:location]=="other" %><li class="active"><% else %><li><% end %>
  <%= link_to 'Other City Jobs', job_location_jobs_path(:location => "other") %></li>


  <li><a href="https://twitter.com/JobTar" class="twitter-follow-button" data-show-count="false" data-size="large">Follow @JobTar</a>
  </li>
  <li style="margin-top: 8px;margin-left: 18px;"><div class="fb-like" data-href="https://www.facebook.com/jobtar" data-layout="button_count" data-width="90" data-show-faces="false"></div>
  </li>

</ul>

<p>Find plenty of job opportunities in India, and end your job search here. If you have job openings in India, you can post your own ad - free!</p>

<table class="table table-bordered table-condensed">
  <thead>
  <tr>
    <th>Posting-Date</th>
    <th>Company</th>
    <th>Location</th>
    <th>Position</th>
    <th>Experience</th>
    <th>Last Date</th>
    <th>Qualification</th>
    <th>Info</th>
    <th>Share</th>
  </tr>
  </thead>
  <tbody>
<% if @jobs.nil? %>
<% else %>
<% @jobs.each do |job| %>
  <tr>
    <td><%= job.created_at.strftime("%d-%m-%Y") %></td>
    <td><%= job.company_name.split[0..1].join(" ") %></td>
    <td><%= job.location %></td>
    <td><%= job.position.split[0..1].join(" ") %></td>
    <td><%= job.experience %></td>
    <td><% if job.qualification.nil? %>ASAP<% else %><%= job.ad_expires_on %><% end %></td>
    <td><%= job.qualification.split[0..1].join(" ") %></td>
    <td><%= link_to 'Details', job %></td>
    <td><a href="https://twitter.com/share" class="twitter-share-button" data-url="http://www.jobtar.com<%= job_path(job) %>" data-text="Hiring for <%= job.company_name %> - <%= job.position %> in <%= job.location %> for <%= job.experience %>" data-via="jobtar" data-count="none" data-hashtags="JOB">Tweet</a>
</td>
  </tr>
<% end %>
<% end %>
  </tbody>
  </table>

<% if @jobs.nil? %>
<% else %>
      <%= will_paginate @jobs, :class => 'digg_pagination'%>
<% end %>



<br />
<p>
<strong>Job Search:</strong>
The Job Ads published on Jobtar are taken automatically from other websites or Jobtar Advertisers. When the Ads are taken from third party websites, Jobtar simply indexes and publishes an extract providing the link to view the full Job Ad published on the site of origin.
</p>
<p>
<strong>Job Alert and Ads via email:</strong>
By providing an email address, you can register for the "Job Alert" Service and receive email notifications about new jobs that match the search filters you set either during registration or at a later time. In addition to notifying you of new Job Ads, the "Job Alert" Service can provide the reception of direct Ads with relevant job vacancies corresponding to the search filters you set.
You can edit your search filters at any time or request that the Service be discontinued. If the User stops interacting with the links on the Job Alert, the Service will stop automatically after some time.
</p>
<p>
<strong>Curriculum Services:</strong>
Jobtar lets you upload your Curriculum Vitae onto the Evenbase Group’s database, making it and the Personal Data contained in your Curriculum Vitae available to recruiters who have subscribed to receive such information by email and/or to search for candidates in the Evenbase Group database using various search criteria (“Curriculum Services”). Curriculum Services are provided by the Evenbase Group and are subject to their legal terms and privacy policy (see www.evenbase.com for more information). You can amend, substitute your Curriculum Vitae or request that Curriculum Services are discontinued at any time.
</p>

app/views/jobs/new.html.erb
<% @title="Free Job Post|Advertisement Jobtar.com}" %>
<h1>Post a Job/ Walk-In / Consultancies</h1>

<%= render 'form' %>

<%= link_to 'Cancel', root_path %>

app/views/jobs/show.html.erb
<% @title="#{@job.company_name} Jobtar.com" %>
<% @meta_tag_desc="Find latest #{@job.company_name} #{@job.position} jobs at JobTar.com. View & Apply to Best Jobs in #{@job.company_name} #{@job.position} & top companies. Submit your resume Free & get selected" %>

<p id="notice"><%= notice %></p>

<div class="fr">
  <a href="https://twitter.com/share" class="twitter-share-button" data-text="Hiring for <%= @job.company_name %> -
  <%= @job.position %> in <%= @job.location %> for
     <%= @job.experience %>" data-via="jobtar" data-count="none" data-hashtags="JOB">Tweet</a>
  <div class="fb-like" data-send="true" data-width="450" data-show-faces="false"></div>
</div>



<p>
  <b>Company name:</b>
  <%= @job.company_name %>
</p>
<% unless @job.company_website.empty? %>
<p>
  <b>Company website:</b>
  <%= @job.company_website %>
</p>
<% end %>
<% unless @job.position.empty? %>
<p>
  <b>Position:</b>
  <%= @job.position %>
</p>
<% end %>
<% unless @job.experience.empty? %>
<p>
  <b>Experience:</b>
  <%= @job.experience %>
</p>
<% end %>
<p>
  <b>Location:</b>
  <%= @job.location %>
</p>

<p>
  <b>Ad posting on:</b>
  <%= @job.created_at %>
</p>
<% unless @job.qualification.empty? %>
<p>
  <b>Ad expires on:</b>
  <%= @job.ad_expires_on %>
</p>
<% end %>
<% unless @job.qualification.empty? %>
<p>
  <b>Qualification:</b>
  <%= @job.qualification %>
</p>
<% end %>
<% unless @job.contact_name.empty? %>
<p>
  <b>Contact name:</b>
  <%= @job.contact_name %>
</p>
<% end %>
<% unless @job.contact_email.empty? %>
<p>
  <b>Contact email:</b>
  <%= @job.contact_email %>
</p>
<% end %>
<% unless @job.contact_number.empty? %>
<p>
  <b>Contact number:</b>
  <%= @job.contact_number %>
</p>
<% end %>
<p>
  <b>Job Summary:</b>
  <%= raw @job.responsibility %>
</p>
<% unless @job.skill.empty? %>
<p>
  <b>Skill:</b>
  <%= raw @job.skill %>
</p>
<% end %>

<%#= link_to 'Edit', edit_job_path(@job) %>
<%#= link_to 'Back', jobs_path %>
<br>
<br>
<br>
<div>
<div class="fb-comments" data-href="http://www.jobtar.com" data-width="470" data-num-posts="3"></div>
</div>

<div id="fb-root"></div>
<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>



    <ul class="nav nav-pills">
    <li><a href="http://www.homelearningcollege.com"> Training courses & online learning </a></li>
    <li><a href="http://www.learningpeople.co.uk">IT & Project Management courses </a></li>
    <li><%= link_to 'Interview practice', interviewer_path %></li>
    <li><%= link_to 'Redundancy advice', redundancyadvice_path %></li>
    </ul>