config/routes.rb
Jfeed::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  resources :users

  resources :jobs do
    collection do
      get "job_location"
      get "job_search"
      get  'post_job' => :new
    end
  end

  controller :information do
    get "contact"
    get "about"
    get "sitemap_ibo"
    get "interviewer"
    get "redundancyadvice"
  end

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  mount Ckeditor::Engine => "/ckeditor"

   root :to => 'jobs#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= @title %></title>
  <style type="text/css">
      body {
          padding-top: 80px;
          padding-bottom: 40px;
      }
  </style>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "ckeditor/init" %>
  <%= csrf_meta_tags %>
  <meta name="keywords content="<%= @title.split[0..2].join(" ") rescue 'JobTar' %>">
  <meta name="description" content="<%= @meta_tag_desc %>">
</head>
<body>

<!-- top menu start-->
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner" style="padding: 10px 20px;">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to 'JobTar', root_path, :class => "brand", :style => "color:#ffffff" %>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li class="active"><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'Post A Job', post_job_jobs_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Job Types <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Walk-ins', job_search_jobs_path(:search => 'Walk-in') %></li>
              <li><%= link_to 'Freshers Jobs', job_search_jobs_path(:search => 'Fresher') %></li>
              <li class="divider"></li>
              <li class="nav-header">More</li>
              <li><%= link_to 'IT Jobs', job_search_jobs_path(:search => 'Software') %></li>
              <li><%= link_to 'Bank Jobs', job_search_jobs_path(:search => 'Bank') %></li>
              <li><%= link_to 'GOVT. Jobs', job_search_jobs_path(:search => 'Govt') %></li>
              <li><%= link_to 'BPO Jobs', job_search_jobs_path(:search => 'BPO') %></li>
            </ul>
          </li>
          <li><%= link_to 'About', about_path %></li>
          <li><%= link_to 'Contact', contact_path %></li>
        </ul>
        <!--
        <form class="navbar-form pull-right">
          <input class="span2" type="text" placeholder="Email">
          <input class="span2" type="password" placeholder="Password">
          <button type="submit" class="btn">Sign in</button>
        </form> -->
         <%= form_tag job_search_jobs_path, :method => 'get', :class => "navbar-search pull-right", :multipart => true do %>
          <div class="input-append">
            <%= text_field_tag 'search', nil, :class => "search-query",:placeholder => 'search for job' %>
          </div>
        <% end %>

      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>
<!-- top menu end -->
<div class="container">

  <div class="row">
    <div class="span4">
    </div>
    <div class="span4">
    </div>
    <div class="span4">
    </div>
  </div>

<%= yield %>
  <hr>
  <footer>
    <p>&copy; JobTar PVT. LTD. 2010</p>
  </footer>
</div>

<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

<div id="fb-root"></div>
<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

</body>
</html>